[[redirects]]
from = "/*"
to = "index.html"
status = 200

[build]
  command = "npm run build"
  functions = "functions"

[dev]
  framework = "# Not needed for build"

[context.production.environment]
  PORT = 3001
  CORS_ORIGIN = "http://localhost:3000"
  VITE_REACT_APP_API_URL = "http://localhost:3001"